services:
  # Admin Service API
  - type: web
    name: admin-service
    env: docker
    rootDir: admin_service
    dockerfilePath: ./Dockerfile
    envVars:      - key: DATABASE_URL
        fromDatabase:
          name: admin-service-db
          property: connectionString
      - key: DB_HOST
        fromDatabase:
          name: admin-service-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: admin-service-db
          property: port
      - key: DB_USER
        fromDatabase:
          name: admin-service-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: admin-service-db
          property: password
      - key: DB_NAME
        value: admin_service
      - key: ENVIRONMENT
        value: production
      - key: API_V1_STR
        value: /api/v1
      - key: PROJECT_NAME
        value: ZCare Admin Service
      - key: CORS_ORIGINS
        value: '["https://your-frontend-url.com"]'
    healthCheckPath: /api/v1/health

databases:
  # PostgreSQL database
  - name: admin-service-db
    plan: free
    databaseName: admin_service
    ipAllowList: []