services:
  # Admin Service API
  - type: web
    name: admin-service
    env: python
    rootDir: admin_service
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: admin-postgres
          property: connectionString
      - key: DB_HOST
        fromDatabase:
          name: admin-postgres
          property: host
      - key: DB_PORT
        fromDatabase:
          name: admin-postgres
          property: port
      - key: DB_USER
        fromDatabase:
          name: admin-postgres
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: admin-postgres
          property: password
      - key: DB_NAME
        fromDatabase:
          name: admin-postgres
          property: database
      - key: ENVIRONMENT
        value: production
      - key: API_V1_STR
        value: /api/v1
      - key: PROJECT_NAME
        value: ZCare Admin Service
      - key: CORS_ORIGINS
        value: '["https://your-frontend-url.com"]'
    healthCheckPath: /api/v1/health

databases:
  # PostgreSQL database
  - name: admin-postgres
    plan: standard
    ipAllowList: [] # Allow all IPs